In [19]:
#Importing libraries
import pandas as pd
import numpy as np
# Display all columns
pd.set_option('display.max_columns', None)

# Display all rows (use carefully)
pd.set_option('display.max_rows', 100)

In [21]:
#Load the dataset
users = pd.read_csv('/content/users.csv')
drivers = pd.read_csv('/content/drivers.csv')
rides = pd.read_csv('/content/rides.csv')

In [22]:
print(users.head())
print(rides.head())
print(drivers.head())

   user_id               name                          email  \
0        1        Tammy Jones  trevinojacqueline@example.net
1        2      Tyler Mathews              tim47@example.com
2        3  Melissa Robertson            scott64@example.org
3        4       Heather Wolf         rushandrew@example.net
4        5      Daniel Daniel           robert13@example.org

        phone_number    registration_date  age  gender           location
0   530-318-6905x290  2024-07-29 12:00:05   21   Other       New Alanside
1  (222)541-3246x834  2021-10-04 14:21:09   53    Male   New Virginiabury
2   309-644-3534x739  2022-10-07 04:46:44   57    Male         Ethanmouth
3  998-772-1220x9334  2022-07-10 14:01:22   50    Male  South Theresaland
4    +1-992-853-1435  2020-05-21 04:37:46   32  Female          New James
   ride_id  user_id start_location     end_location      ride_start_time  \
0        1     4067   Larryborough    Norrisborough  2024-04-30 10:31:56
1        2     9160    Williamston      Robertburgh  2024-09-11 12:07:26
2        3     1990      Howeshire  Christopherland  2024-04-30 10:21:25
3        4     1268   North Annton     East Heather  2024-04-12 04:06:58
4        5     7296   South Joseph  Lake Samuelberg  2024-04-26 16:45:45

         ride_end_time  distance_km  fare_amount  driver_id
0  2024-04-30 11:05:56         2.03         3.33        145
1  2024-09-11 13:34:26        13.66        30.03        244
2  2024-04-30 10:40:25         5.50        15.67        234
3  2024-04-12 05:07:58        31.74        53.90        145
4  2024-04-26 18:31:45        13.54        38.40         39
   driver_id                name  vehicle_id  rating  total_rides  available
0          1    Virginia Johnson         284    3.44           30       True
1          2       Daniel Maddox          18    2.59           61      False
2          3    Patricia Salazar         298    4.93           75       True
3          4  Cameron Hinton DDS          49    2.59           12       True
4          5      Jennifer Ayala         138    4.69           71       True

In [23]:
print("Drivers:", drivers.shape)
print("Users:", users.shape)
print("Rides:", rides.shape)

Drivers: (300, 6)
Users: (10000, 8)
Rides: (50000, 9)

In [24]:
print("Users")
users.info()

print("\nDrivers")
drivers.info()

print("\nRides")
rides.info()

Users
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   user_id            10000 non-null  int64
 1   name               10000 non-null  object
 2   email              10000 non-null  object
 3   phone_number       10000 non-null  object
 4   registration_date  10000 non-null  object
 5   age                10000 non-null  int64
 6   gender             10000 non-null  object
 7   location           10000 non-null  object
dtypes: int64(2), object(6)
memory usage: 625.1+ KB

Drivers
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   driver_id    300 non-null    int64
 1   name         300 non-null    object
 2   vehicle_id   300 non-null    int64
 3   rating       300 non-null    float64
 4   total_rides  300 non-null    int64
 5   available    300 non-null    bool
dtypes: bool(1), float64(1), int64(3), object(1)
memory usage: 12.1+ KB

Rides
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ride_id          50000 non-null  int64
 1   user_id          50000 non-null  int64
 2   start_location   50000 non-null  object
 3   end_location     50000 non-null  object
 4   ride_start_time  50000 non-null  object
 5   ride_end_time    50000 non-null  object
 6   distance_km      50000 non-null  float64
 7   fare_amount      50000 non-null  float64
 8   driver_id        50000 non-null  int64
dtypes: float64(2), int64(3), object(4)
memory usage: 3.4+ MB

In [25]:
#check missing values
print("Users")
print(users.isnull().sum())

print("\nDrivers")
print(drivers.isnull().sum())

print("\nRides")
print(rides.isnull().sum())

Users
user_id              0
name                 0
email                0
phone_number         0
registration_date    0
age                  0
gender               0
location             0
dtype: int64

Drivers
driver_id      0
name           0
vehicle_id     0
rating         0
total_rides    0
available      0
dtype: int64

Rides
ride_id            0
user_id            0
start_location     0
end_location       0
ride_start_time    0
ride_end_time      0
distance_km        0
fare_amount        0
driver_id          0
dtype: int64

In [26]:
#checl duplicate rows
print("Users")
print(users.duplicated().sum())

print("\nDrivers")
print(drivers.duplicated().sum())

print("\nRides")
print(rides.duplicated().sum())

Users
0

Drivers
0

Rides
0

In [27]:
users.describe(include="all")

,user_id,name,email,phone_number,registration_date,age,gender,location
count,10000.00000,10000,10000,10000,10000,10000.000000,10000,10000
unique,NaN,9315,9807,10000,10000,NaN,3,7787
top,NaN,Elizabeth Williams,dbrown@example.org,7808975705,2023-12-21 09:10:43,NaN,Other,East Michael
freq,NaN,6,4,1,1,NaN,3361,18
mean,5000.50000,NaN,NaN,NaN,NaN,41.161400,NaN,NaN
std,2886.89568,NaN,NaN,NaN,NaN,13.950914,NaN,NaN
min,1.00000,NaN,NaN,NaN,NaN,18.000000,NaN,NaN
25%,2500.75000,NaN,NaN,NaN,NaN,29.000000,NaN,NaN
50%,5000.50000,NaN,NaN,NaN,NaN,41.000000,NaN,NaN
75%,7500.25000,NaN,NaN,NaN,NaN,53.000000,NaN,NaN
max,10000.00000,NaN,NaN,NaN,NaN,65.000000,NaN,NaN

In [28]:
drivers.describe(include="all")

,driver_id,name,vehicle_id,rating,total_rides,available
count,300.000000,300,300.000000,300.000000,300.00000,300
unique,NaN,298,NaN,NaN,NaN,2
top,NaN,Christopher Miller,NaN,NaN,NaN,False
freq,NaN,2,NaN,NaN,NaN,155
mean,150.500000,NaN,152.633333,2.975867,100.79000,NaN
std,86.746758,NaN,87.064495,1.189947,52.76761,NaN
min,1.000000,NaN,2.000000,1.010000,11.00000,NaN
25%,75.750000,NaN,81.750000,1.860000,56.00000,NaN
50%,150.500000,NaN,147.000000,2.955000,96.00000,NaN
75%,225.250000,NaN,229.000000,4.032500,143.00000,NaN
max,300.000000,NaN,300.000000,5.000000,199.00000,NaN

In [29]:
rides.describe(include="all")

,ride_id,user_id,start_location,end_location,ride_start_time,ride_end_time,distance_km,fare_amount,driver_id
count,50000.000000,50000.000000,50000,50000,50000,50000,50000.000000,50000.000000,50000.00000
unique,NaN,NaN,25069,25025,49933,49944,NaN,NaN,NaN
top,NaN,NaN,South Michael,Port Michael,2024-03-16 18:33:31,2024-06-16 20:29:30,NaN,NaN,NaN
freq,NaN,NaN,50,53,2,3,NaN,NaN,NaN
mean,25000.500000,5004.148820,NaN,NaN,NaN,NaN,25.535241,57.431624,150.65168
std,14433.901067,2894.760445,NaN,NaN,NaN,NaN,14.156627,34.260297,86.68590
min,1.000000,1.000000,NaN,NaN,NaN,NaN,1.000000,1.570000,1.00000
25%,12500.750000,2487.000000,NaN,NaN,NaN,NaN,13.220000,28.670000,76.00000
50%,25000.500000,5028.000000,NaN,NaN,NaN,NaN,25.540000,55.290000,151.00000
75%,37500.250000,7516.000000,NaN,NaN,NaN,NaN,37.890000,82.010000,226.00000
max,50000.000000,10000.000000,NaN,NaN,NaN,NaN,50.000000,149.130000,300.00000

In [30]:
# Check whether user_id is unique

print("Total Users :", len(users))
print("Unique User IDs :", users['user_id'].nunique())

Total Users : 10000
Unique User IDs : 10000

In [31]:
print("duplicated_email:", users['email'].duplicated().sum())
print("duplicated_phone_number:", users['phone_number'].duplicated().sum())

duplicated_email: 193
duplicated_phone_number: 0

In [32]:
#Age validation
users['age'].describe()

count    10000.000000
mean        41.161400
std         13.950914
min         18.000000
25%         29.000000
50%         41.000000
75%         53.000000
max         65.000000
Name: age, dtype: float64

In [33]:
users[users['age'] < 18]

Empty DataFrame
Columns: [user_id, name, email, phone_number, registration_date, age, gender, location]
Index: []

In [34]:
users[users['age'] > 100]

Empty DataFrame
Columns: [user_id, name, email, phone_number, registration_date, age, gender, location]
Index: []

In [35]:
users['gender'].value_counts()

gender
Other     3361
Female    3326
Male      3313
Name: count, dtype: int64

In [36]:
users['registration_date'] = pd.to_datetime(users['registration_date'])

In [37]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   user_id            10000 non-null  int64
 1   name               10000 non-null  object
 2   email              10000 non-null  object
 3   phone_number       10000 non-null  object
 4   registration_date  10000 non-null  datetime64[ns]
 5   age                10000 non-null  int64
 6   gender             10000 non-null  object
 7   location           10000 non-null  object
dtypes: datetime64[ns](1), int64(2), object(5)
memory usage: 625.1+ KB

In [38]:
print("Total Drivers :", len(drivers))
print("Unique Drivers :", drivers['driver_id'].nunique())

Total Drivers : 300
Unique Drivers : 300

In [39]:
drivers['rating'].describe()

count    300.000000
mean       2.975867
std        1.189947
min        1.010000
25%        1.860000
50%        2.955000
75%        4.032500
max        5.000000
Name: rating, dtype: float64

In [40]:
drivers[(drivers['rating'] < 1) | (drivers['rating'] > 5)]

Empty DataFrame
Columns: [driver_id, name, vehicle_id, rating, total_rides, available]
Index: []

In [41]:
drivers[drivers['total_rides'] < 0]

Empty DataFrame
Columns: [driver_id, name, vehicle_id, rating, total_rides, available]
Index: []

In [42]:
drivers['available'].value_counts()

available
False    155
True     145
Name: count, dtype: int64

In [43]:
print("Total Rides :", len(rides))
print("Unique Ride IDs :", rides['ride_id'].nunique())

Total Rides : 50000
Unique Ride IDs : 50000

In [44]:
rides['distance_km'].describe()

count    50000.000000
mean        25.535241
std         14.156627
min          1.000000
25%         13.220000
50%         25.540000
75%         37.890000
max         50.000000
Name: distance_km, dtype: float64

In [45]:
rides['ride_start_time'] = pd.to_datetime(rides['ride_start_time'])
rides['ride_end_time'] = pd.to_datetime(rides['ride_end_time'])

In [46]:
rides.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ride_id          50000 non-null  int64
 1   user_id          50000 non-null  int64
 2   start_location   50000 non-null  object
 3   end_location     50000 non-null  object
 4   ride_start_time  50000 non-null  datetime64[ns]
 5   ride_end_time    50000 non-null  datetime64[ns]
 6   distance_km      50000 non-null  float64
 7   fare_amount      50000 non-null  float64
 8   driver_id        50000 non-null  int64
dtypes: datetime64[ns](2), float64(2), int64(3), object(2)
memory usage: 3.4+ MB

In [47]:
rides['ride_duration_minutes'] = (
    rides['ride_end_time'] - rides['ride_start_time']
).dt.total_seconds() / 60

In [48]:
rides[['ride_start_time',
       'ride_end_time',
       'ride_duration_minutes']].head()

      ride_start_time       ride_end_time  ride_duration_minutes
0 2024-04-30 10:31:56 2024-04-30 11:05:56                   34.0
1 2024-09-11 12:07:26 2024-09-11 13:34:26                   87.0
2 2024-04-30 10:21:25 2024-04-30 10:40:25                   19.0
3 2024-04-12 04:06:58 2024-04-12 05:07:58                   61.0
4 2024-04-26 16:45:45 2024-04-26 18:31:45                  106.0

#Feature Engineering

In [49]:
# Create Ride Date
rides['ride_date'] = rides['ride_start_time'].dt.date

In [50]:
rides[['ride_start_time', 'ride_date']].head()

      ride_start_time   ride_date
0 2024-04-30 10:31:56  2024-04-30
1 2024-09-11 12:07:26  2024-09-11
2 2024-04-30 10:21:25  2024-04-30
3 2024-04-12 04:06:58  2024-04-12
4 2024-04-26 16:45:45  2024-04-26

In [51]:
# Extract Ride Hour
rides['ride_hour'] = rides['ride_start_time'].dt.hour

In [52]:
rides[['ride_start_time', 'ride_hour']].head()

      ride_start_time  ride_hour
0 2024-04-30 10:31:56         10
1 2024-09-11 12:07:26         12
2 2024-04-30 10:21:25         10
3 2024-04-12 04:06:58          4
4 2024-04-26 16:45:45         16

In [53]:
# Day of Week
rides['day_name'] = rides['ride_start_time'].dt.day_name()

In [54]:
rides[['ride_start_time', 'day_name']].head()

      ride_start_time   day_name
0 2024-04-30 10:31:56    Tuesday
1 2024-09-11 12:07:26  Wednesday
2 2024-04-30 10:21:25    Tuesday
3 2024-04-12 04:06:58     Friday
4 2024-04-26 16:45:45     Friday

In [55]:
# Month Name
rides['month'] = rides['ride_start_time'].dt.month_name()

In [56]:
rides[['ride_start_time', 'month']].head()

      ride_start_time      month
0 2024-04-30 10:31:56      April
1 2024-09-11 12:07:26  September
2 2024-04-30 10:21:25      April
3 2024-04-12 04:06:58      April
4 2024-04-26 16:45:45      April

In [57]:
# Quarter
rides['quarter'] = rides['ride_start_time'].dt.quarter

In [58]:
# Year
rides['year'] = rides['ride_start_time'].dt.year

In [59]:
# Weekend Flag
rides['weekend_flag'] = rides['day_name'].isin(['Saturday', 'Sunday'])

In [60]:
rides['weekend_flag'].value_counts()

weekend_flag
False    36034
True     13966
Name: count, dtype: int64

In [61]:
# Time sot
def time_slot(hour):
    if 0 <= hour < 6:
        return 'Late Night'
    elif 6 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 17:
        return 'Afternoon'
    elif 17 <= hour < 22:
        return 'Evening'
    else:
        return 'Night'

In [62]:
rides['time_slot'] = rides['ride_hour'].apply(time_slot)

In [63]:
rides['time_slot'].value_counts()

time_slot
Morning       12579
Late Night    12437
Evening       10397
Afternoon     10361
Night          4226
Name: count, dtype: int64

In [64]:
# Fare per Km
rides['fare_per_km'] = (
    rides['fare_amount'] / rides['distance_km']
).round(2)

In [65]:
rides[['fare_amount', 'distance_km', 'fare_per_km']].head()

   fare_amount  distance_km  fare_per_km
0         3.33         2.03         1.64
1        30.03        13.66         2.20
2        15.67         5.50         2.85
3        53.90        31.74         1.70
4        38.40        13.54         2.84

In [66]:
#Trip category
def trip_category(distance):
    if distance < 5:
        return 'Short'
    elif distance <= 15:
        return 'Medium'
    else:
        return 'Long'

In [67]:
rides['trip_category'] = rides['distance_km'].apply(trip_category)

In [68]:
rides['trip_category'].value_counts()

trip_category
Long      35624
Medium    10341
Short      4035
Name: count, dtype: int64

In [69]:
rides.head()

,ride_id,user_id,start_location,end_location,ride_start_time,ride_end_time,distance_km,fare_amount,driver_id,ride_duration_minutes,ride_date,ride_hour,day_name,month,quarter,year,weekend_flag,time_slot,fare_per_km,trip_category
0,1,4067,Larryborough,Norrisborough,2024-04-30 10:31:56,2024-04-30 11:05:56,2.03,3.33,145,34.0,2024-04-30,10,Tuesday,April,2,2024,False,Morning,1.64,Short
1,2,9160,Williamston,Robertburgh,2024-09-11 12:07:26,2024-09-11 13:34:26,13.66,30.03,244,87.0,2024-09-11,12,Wednesday,September,3,2024,False,Afternoon,2.20,Medium
2,3,1990,Howeshire,Christopherland,2024-04-30 10:21:25,2024-04-30 10:40:25,5.50,15.67,234,19.0,2024-04-30,10,Tuesday,April,2,2024,False,Morning,2.85,Medium
3,4,1268,North Annton,East Heather,2024-04-12 04:06:58,2024-04-12 05:07:58,31.74,53.90,145,61.0,2024-04-12,4,Friday,April,2,2024,False,Late Night,1.70,Long
4,5,7296,South Joseph,Lake Samuelberg,2024-04-26 16:45:45,2024-04-26 18:31:45,13.54,38.40,39,106.0,2024-04-26,16,Friday,April,2,2024,False,Afternoon,2.84,Medium

In [70]:
rides['month_number'] = rides['ride_start_time'].dt.month
rides['month_name'] = rides['ride_start_time'].dt.month_name()

In [71]:
# Check all columns
print(users.columns)
print("\n")
print(drivers.columns)
print("\n")
print(rides.columns)

Index(['user_id', 'name', 'email', 'phone_number', 'registration_date', 'age',
       'gender', 'location'],
      dtype='object')


Index(['driver_id', 'name', 'vehicle_id', 'rating', 'total_rides',
       'available'],
      dtype='object')


Index(['ride_id', 'user_id', 'start_location', 'end_location',
       'ride_start_time', 'ride_end_time', 'distance_km', 'fare_amount',
       'driver_id', 'ride_duration_minutes', 'ride_date', 'ride_hour',
       'day_name', 'month', 'quarter', 'year', 'weekend_flag', 'time_slot',
       'fare_per_km', 'trip_category', 'month_number', 'month_name'],
      dtype='object')

In [72]:
#Reorder columns
rides = rides[
[
'ride_id',
'user_id',
'driver_id',

'start_location',
'end_location',

'ride_start_time',
'ride_end_time',

'ride_date',
'ride_hour',
'day_name',

'month_number',
'month_name',

'quarter',
'year',

'weekend_flag',
'time_slot',

'distance_km',
'ride_duration_minutes',

'fare_amount',
'fare_per_km',

'trip_category'
]
]

In [73]:
import os

# Create the directory if it doesn't exist
output_dir = "../Cleaned_Data"
os.makedirs(output_dir, exist_ok=True)

users.to_csv(os.path.join(output_dir, "clean_users.csv"), index=False)

drivers.to_csv(os.path.join(output_dir, "clean_drivers.csv"), index=False)

rides.to_csv(os.path.join(output_dir, "clean_rides.csv"), index=False)

In [74]:
users.to_csv("clean_users.csv", index=False)
drivers.to_csv("clean_drivers.csv", index=False)
rides.to_csv("clean_rides.csv", index=False)

In [76]:
drivers['vehicle_id'].duplicated().sum()

np.int64(111)

In [77]:
drivers[drivers['vehicle_id'].duplicated(keep=False)].sort_values('vehicle_id')

     driver_id              name  vehicle_id  rating  total_rides  available
44          45    Patricia Smith           8    4.09           84       True
96          97   Veronica Harris           8    1.48           43       True
144        145       Kelly Smith           8    4.47           52       True
20          21        Megan Rose           9    2.31           74       True
89          90    Jeremy Ramirez           9    2.30          170      False
..         ...               ...         ...     ...          ...        ...
65          66     Shelby Gibson         289    3.27          172      False
232        233    Andrea Bennett         290    1.29           70       True
22          23    Melinda Miller         290    1.02           53      False
19          20  Christie Johnson         293    1.12          148      False
243        244     Charles Smith         293    1.55           84      False

[188 rows x 6 columns]

In [78]:
users['email'].duplicated().sum()

np.int64(193)

In [79]:
users[users['email'].duplicated(keep=False)].sort_values('email')

,user_id,name,email,phone_number,registration_date,age,gender,location
1484,1485,Carl Anderson,aanderson@example.org,+1-855-322-2241,2022-12-16 01:13:41,38,Female,East Charlesstad
4937,4938,Michael Adkins,aanderson@example.org,+1-348-212-2446x69358,2020-12-15 20:29:42,42,Female,Andersonfort
2407,2408,Alexis Walls,agarcia@example.com,934.748.7699,2023-01-24 07:27:39,41,Other,New Alexandra
1846,1847,Jeffrey Thomas,agarcia@example.com,(213)838-7120x841,2023-11-26 12:26:28,56,Other,Lake William
5736,5737,Paul Griffin,ahernandez@example.net,(285)963-9469,2023-12-29 10:35:16,21,Male,Port Daniel
...,...,...,...,...,...,...,...,...
4184,4185,Joshua Wilson,yjones@example.com,930.930.3209,2023-02-18 00:33:23,55,Male,North Tanner
7032,7033,Jimmy Spencer,ymills@example.com,478-221-5940x7197,2024-09-12 04:18:14,53,Other,Johnsonmouth
6142,6143,Megan Dalton,ymills@example.com,+1-547-991-5488x881,2024-09-19 04:46:12,18,Other,Johnsonshire
9880,9881,Casey Marshall,zjohnson@example.com,785.926.8090x8413,2021-04-10 16:30:33,30,Male,Nobleland
5481,5482,Anna Gallagher,zjohnson@example.com,415.828.6293x70301,2024-08-02 09:11:00,55,Female,Simsshire